---
AWSTemplateFormatVersion: '2010-09-09'
Description: Creates an Ubuntu 16.04 Web Server based on https://github.com/widdix/learn-cloudformation/blob/master/lab0-create-stack/demo.yaml, last access 9/6/2017

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-10547475
      InstanceType: t2.micro
      SecurityGroups: 
      - !Ref WebserverSecurityGroup
      Tags:
      - Key: Name
        Value: Ubuntu16 Web Server
      UserData:
        'Fn::Base64': !Sub |
          #!/bin/bash
          set -e
          set -x
          # Set timezone
          sudo timedatectl set-timezone America/New_York

          sudo apt-get update
          sudo apt-get install -y apache2
          cd /var/www/html
          echo "<h1>Dr. V's CloudFormed Server</h1><p>This page created entirely by CloudFormation</p>" >index.html
  WebserverSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: hello-world-webserver
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: 80
        IpProtocol: tcp
        ToPort: 80
Outputs:
  HelloWorldURL:
    Description: The url pointing to our page.
    Value: !Sub 'http://${EC2Instance.PublicIp}'
          